### ISSUE TITLE
Peer-to-peer code review

### ISSUE THREAD

**Issue by DRT-DISABLED-ACCOUNT** [pradmon/MyPortfolio#4]
### 👋 Hey Jorge

During our code review, we went over the last five commits made and examined the email sent by the code reviewer highlighting possible areas for improvement. We addressed the input border color issue by implementing changes to match the design specifications in Figma. Additionally, we provided guidance on using developer tools selection to achieve the desired border-radius. Overall, the progress made has been excellent, and we commend the developer for a job well done.

**By Fortune Uzodinma and Juan Velez** 👍

**Comment by pradmon** [comment]
Thanks, partners.
